# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moringa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('codelink', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('sitelink', models.CharField(max_length=255)),
                ('published', models.DateField(verbose_name='Date')),
                ('features', models.ManyToManyField(to='moringa.features')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pic', models.ImageField(blank=True, upload_to='projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moringa.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moringa.Project')),
            ],
        ),
    ]
