# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moringa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood',
            field=models.CharField(choices=[('South B', 'South B'), ('Makongeni', 'Makongeni'), ('Kileleshwa', 'Kileleshwa')], max_length=255),
        ),
    ]
