# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moringa', '0002_auto_20190606_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('detailtype', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moringa.Neighbourhood')),
            ],
        ),
    ]
