# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moringa', '0002_features_project_projectpictures_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpictures',
            name='pic',
            field=models.ImageField(default='projects/beauty1.jpg', upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('Usability', 'Usability'), ('Design', 'Design'), ('Content', 'Content')], max_length=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
    ]
