# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moringa', '0003_hooddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hooddetails',
            name='detailtype',
            field=models.CharField(choices=[('Contact', 'Contact'), ('Business', 'Business')], max_length=255),
        ),
    ]
