# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moringa', '0003_auto_20190606_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpictures',
            old_name='name',
            new_name='projectpicture',
        ),
    ]
