# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moringa', '0004_auto_20190606_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/beauty1.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projectpictures',
            name='pic',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
